/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesar_privatemusik;

import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.HashMap;

/**
 *
 * @author Ronaldo
 */
public class Beranda extends javax.swing.JFrame {
    int mousePX;
    int mousePY;
    public String totalsiswa;
    public String totalpengajar;
    public HashMap<String,UserHashMap> daftarpengajar = new HashMap<>();
    public HashMap<String,UserHashMap> daftarsiswa = new HashMap<>();
    

    /**
     * Creates new form Beranda
     */
    public Beranda() {
        initComponents();
        setLocationRelativeTo(null);
        
        UserSession.setUserLogin("");
        jumlahsiswa();
        jumlahpengajar();
        //jumlah("select Id_Pengajar,Nama_Siswa from pengajar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mize = new javax.swing.JLabel();
        tutup3 = new javax.swing.JLabel();
        loginsiswa = new javax.swing.JLabel();
        loginadmin = new javax.swing.JLabel();
        help = new javax.swing.JLabel();
        contactus = new javax.swing.JLabel();
        aboutus = new javax.swing.JLabel();
        registrasisiswa = new javax.swing.JLabel();
        loginguru = new javax.swing.JLabel();
        registrasiguru = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        mize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mize.setForeground(new java.awt.Color(255, 255, 255));
        mize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonMinimize.png"))); // NOI18N
        mize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mizeMouseClicked(evt);
            }
        });
        getContentPane().add(mize);
        mize.setBounds(740, 0, 20, 30);

        tutup3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tutup3.setForeground(new java.awt.Color(255, 255, 255));
        tutup3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonExit.png"))); // NOI18N
        tutup3.setText("X");
        tutup3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tutup3.setPreferredSize(new java.awt.Dimension(20, 20));
        tutup3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutup3MouseClicked(evt);
            }
        });
        getContentPane().add(tutup3);
        tutup3.setBounds(770, 0, 20, 30);

        loginsiswa.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 14)); // NOI18N
        loginsiswa.setForeground(new java.awt.Color(255, 255, 255));
        loginsiswa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loginsiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginsiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginsiswaMouseClicked(evt);
            }
        });
        getContentPane().add(loginsiswa);
        loginsiswa.setBounds(0, 380, 140, 40);

        loginadmin.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        loginadmin.setForeground(new java.awt.Color(255, 255, 255));
        loginadmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginadmin.setText("Login Admin");
        loginadmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginadminMouseClicked(evt);
            }
        });
        getContentPane().add(loginadmin);
        loginadmin.setBounds(410, 230, 140, 40);

        help.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        help.setForeground(new java.awt.Color(255, 255, 255));
        help.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        help.setText("Help");
        help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMouseClicked(evt);
            }
        });
        getContentPane().add(help);
        help.setBounds(410, 480, 140, 40);

        contactus.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        contactus.setForeground(new java.awt.Color(255, 255, 255));
        contactus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contactus.setText("Contact Us");
        contactus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contactus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactusMouseClicked(evt);
            }
        });
        getContentPane().add(contactus);
        contactus.setBounds(610, 480, 140, 40);

        aboutus.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        aboutus.setForeground(new java.awt.Color(255, 255, 255));
        aboutus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutus.setText("About US");
        aboutus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutusMouseClicked(evt);
            }
        });
        getContentPane().add(aboutus);
        aboutus.setBounds(210, 480, 140, 40);

        registrasisiswa.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        registrasisiswa.setForeground(new java.awt.Color(255, 255, 255));
        registrasisiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrasisiswa.setText("Registration");
        registrasisiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrasisiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrasisiswaMouseClicked(evt);
            }
        });
        getContentPane().add(registrasisiswa);
        registrasisiswa.setBounds(610, 230, 140, 40);

        loginguru.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 14)); // NOI18N
        loginguru.setForeground(new java.awt.Color(255, 255, 255));
        loginguru.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loginguru.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginguru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginguruMouseClicked(evt);
            }
        });
        getContentPane().add(loginguru);
        loginguru.setBounds(0, 430, 140, 30);

        registrasiguru.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        registrasiguru.setForeground(new java.awt.Color(255, 255, 255));
        registrasiguru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrasiguru.setText("Registration");
        registrasiguru.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrasiguru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrasiguruMouseClicked(evt);
            }
        });
        getContentPane().add(registrasiguru);
        registrasiguru.setBounds(210, 230, 140, 40);

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundBeranda.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrasiguruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrasiguruMouseClicked
        // TODO add your handling code here:
        dispose();
        new PendaftaranPengajar().setVisible(true);
    }//GEN-LAST:event_registrasiguruMouseClicked

    private void loginguruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginguruMouseClicked
        // TODO add your handling code here:
        dispose();
        new LoginPengajar().setVisible(true);
    }//GEN-LAST:event_loginguruMouseClicked

    private void registrasisiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrasisiswaMouseClicked
        // TODO add your handling code here:
        dispose();
        new PendaftaranSiswa().setVisible(true);
    }//GEN-LAST:event_registrasisiswaMouseClicked

    private void aboutusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutusMouseClicked
        // TODO add your handling code here:
        dispose();
        new AboutUs().setVisible(true);
    }//GEN-LAST:event_aboutusMouseClicked

    private void helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseClicked
        // TODO add your handling code here:
        dispose();
        new Help().setVisible(true);
    }//GEN-LAST:event_helpMouseClicked

    private void contactusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactusMouseClicked
        // TODO add your handling code here:
        dispose();
        new ContactUs().setVisible(true);
    }//GEN-LAST:event_contactusMouseClicked

    private void loginadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginadminMouseClicked
        // TODO add your handling code here:
        dispose();
        new LoginAdmin().setVisible(true);
    }//GEN-LAST:event_loginadminMouseClicked

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
        int koordinatX = evt.getXOnScreen();
        int koordinatY = evt.getYOnScreen();
        
        this.setLocation(koordinatX-mousePX, koordinatY-mousePY);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void loginsiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginsiswaMouseClicked
        // TODO add your handling code here:
        dispose();
        new LoginSiswa().setVisible(true);    
    }//GEN-LAST:event_loginsiswaMouseClicked

    private void tutup3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutup3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tutup3MouseClicked

    private void mizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mizeMouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_mizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }

    public void jumlahsiswa(){        
        UserHashMap s;
        try{
            MysqlDataSource submit = new MysqlDataSource();
            submit.setServerName("localhost");
            submit.setUser("root");
            submit.setPassword("");
            submit.setPortNumber(3306);
            submit.setDatabaseName("private_musik");
            
            Connection koneksi=submit.getConnection();
            
            ResultSet rs = koneksi.prepareStatement("select Id_Siswa,Nama_Siswa from siswa").executeQuery();
                while(rs.next()){
                    String id = rs.getString(1);
                    String nama = rs.getString(2);
                    s = new UserHashMap(id,nama);
                    daftarsiswa.put(s.id, s);
                }
                
                totalsiswa=String.valueOf(daftarsiswa.size());
        }catch(Exception e){
            System.out.println(e);
            
        }
    }
    
    public void jumlahpengajar(){        
        UserHashMap p;
        try{
            MysqlDataSource submit = new MysqlDataSource();
            submit.setServerName("localhost");
            submit.setUser("root");
            submit.setPassword("");
            submit.setPortNumber(3306);
            submit.setDatabaseName("private_musik");
            
            Connection koneksi=submit.getConnection();
            
            ResultSet rs = koneksi.prepareStatement("select Id_Pengajar,Nama_Pengajar from pengajar").executeQuery();
                while(rs.next()){
                    String id = rs.getString(1);
                    String nama = rs.getString(2);
                    p = new UserHashMap(id,nama);
                    daftarpengajar.put(p.id, p);
                }
                
                totalpengajar=String.valueOf(daftarpengajar.size());
        }catch(Exception e){
            System.out.println(e);
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutus;
    private javax.swing.JLabel contactus;
    private javax.swing.JLabel help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel loginadmin;
    private javax.swing.JLabel loginguru;
    private javax.swing.JLabel loginsiswa;
    private javax.swing.JLabel mize;
    private javax.swing.JLabel registrasiguru;
    private javax.swing.JLabel registrasisiswa;
    private javax.swing.JLabel tutup3;
    // End of variables declaration//GEN-END:variables
}
