/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesar_privatemusik;

import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronaldo
 */
public class EditProfilePengajar extends javax.swing.JFrame {
    int mousePX;
    int mousePY;
    /**
     * Creates new form EditProfilePengajar
     */
    public EditProfilePengajar() {
        initComponents();
        setLocationRelativeTo(null);
        
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tutup = new javax.swing.JLabel();
        mize = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtalatmusikpengajar = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtidpengajar = new javax.swing.JTextField();
        txtnamapengajar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamatpengajar = new javax.swing.JTextArea();
        txtkelaminpengajar = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        tutup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tutup.setForeground(new java.awt.Color(255, 255, 255));
        tutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonExit.png"))); // NOI18N
        tutup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tutup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutupMouseClicked(evt);
            }
        });
        getContentPane().add(tutup);
        tutup.setBounds(570, 0, 20, 30);

        mize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mize.setForeground(new java.awt.Color(255, 255, 255));
        mize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonMinimize.png"))); // NOI18N
        mize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mizeMouseClicked(evt);
            }
        });
        getContentPane().add(mize);
        mize.setBounds(550, 0, 20, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonUpdate.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 330, 100, 30);

        jLabel8.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonBack.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 330, 100, 30);

        txtalatmusikpengajar.setBackground(new java.awt.Color(204, 204, 204));
        txtalatmusikpengajar.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 11)); // NOI18N
        txtalatmusikpengajar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0. Gitar", "1. Piano", "2. Bass", "3. Drum", "4. Saxophone", "5. Biola" }));
        txtalatmusikpengajar.setBorder(null);
        txtalatmusikpengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalatmusikpengajarActionPerformed(evt);
            }
        });
        getContentPane().add(txtalatmusikpengajar);
        txtalatmusikpengajar.setBounds(240, 260, 90, 30);

        jLabel2.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 153));
        jLabel2.setText("Jenis Alat Musik");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 260, 160, 23);

        txtidpengajar.setEditable(false);
        txtidpengajar.setBackground(new java.awt.Color(204, 204, 204));
        txtidpengajar.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 18)); // NOI18N
        txtidpengajar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidpengajar.setBorder(null);
        txtidpengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpengajarActionPerformed(evt);
            }
        });
        getContentPane().add(txtidpengajar);
        txtidpengajar.setBounds(240, 70, 220, 30);

        txtnamapengajar.setBackground(new java.awt.Color(204, 204, 204));
        txtnamapengajar.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 18)); // NOI18N
        txtnamapengajar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnamapengajar.setBorder(null);
        txtnamapengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamapengajarActionPerformed(evt);
            }
        });
        txtnamapengajar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnamapengajarKeyTyped(evt);
            }
        });
        getContentPane().add(txtnamapengajar);
        txtnamapengajar.setBounds(240, 110, 220, 30);

        jLabel7.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 153));
        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 190, 80, 23);

        jLabel3.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 153));
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 110, 60, 20);

        txtalamatpengajar.setBackground(new java.awt.Color(204, 204, 204));
        txtalamatpengajar.setColumns(20);
        txtalamatpengajar.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtalamatpengajar.setRows(5);
        txtalamatpengajar.setBorder(null);
        jScrollPane1.setViewportView(txtalamatpengajar);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 190, 300, 60);

        txtkelaminpengajar.setBackground(new java.awt.Color(204, 204, 204));
        txtkelaminpengajar.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 11)); // NOI18N
        txtkelaminpengajar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-Laki", "Perempuan" }));
        txtkelaminpengajar.setBorder(null);
        txtkelaminpengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkelaminpengajarActionPerformed(evt);
            }
        });
        getContentPane().add(txtkelaminpengajar);
        txtkelaminpengajar.setBounds(240, 150, 89, 30);

        jLabel6.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 153));
        jLabel6.setText("Jenis Kelamin");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 150, 130, 23);

        jLabel4.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 153));
        jLabel4.setText("Id Pengajar");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 70, 130, 20);

        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel9MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 600, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundEditProfile_1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtalatmusikpengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalatmusikpengajarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalatmusikpengajarActionPerformed

    private void txtidpengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpengajarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpengajarActionPerformed

    private void txtnamapengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamapengajarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamapengajarActionPerformed

    private void txtkelaminpengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkelaminpengajarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkelaminpengajarActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        dispose();
        new FormPengajar().setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        String nama=txtnamapengajar.getText();
        String alamat=txtalamatpengajar.getText();
        if(nama.equals("")||alamat.equals("")){
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!");
        }else{
            try{
                MysqlDataSource submit = new MysqlDataSource();
                submit.setServerName("localhost");
                submit.setUser("root");
                submit.setPassword("");
                submit.setPortNumber(3306);
                submit.setDatabaseName("private_musik");

                Connection koneksi=submit.getConnection();

                koneksi.prepareStatement(
                    "update pengajar set Nama_Pengajar = '"+txtnamapengajar.getText()+
                    "', Jenis_Kelamin = '"+txtkelaminpengajar.getSelectedItem()+
                    "', Alamat = '"+txtalamatpengajar.getText()+
                    "', Id_Alat_Musik='"+txtalatmusikpengajar.getSelectedIndex()+
                    "' where Id_Pengajar = '"+UserSession.getUserLogin()+"' ").execute();

                JOptionPane.showMessageDialog(null, "Profil berhasil diperbaharui!");
                dispose();
                new FormPengajar().setVisible(true);
            }catch(Exception e){
                System.out.println(e);

            }
        }        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void tutupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutupMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tutupMouseClicked

    private void mizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mizeMouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_mizeMouseClicked

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        // TODO add your handling code here:
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseDragged
        // TODO add your handling code here:
        int koordinatX = evt.getXOnScreen();
        int koordinatY = evt.getYOnScreen();

        this.setLocation(koordinatX-mousePX, koordinatY-mousePY);
    }//GEN-LAST:event_jLabel9MouseDragged

    private void txtnamapengajarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamapengajarKeyTyped
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtnamapengajarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfilePengajar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfilePengajar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfilePengajar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfilePengajar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProfilePengajar().setVisible(true);
            }
        });
    }

    public void tampil() {
        try{
            MysqlDataSource submit = new MysqlDataSource();
            submit.setServerName("localhost");
            submit.setUser("root");
            submit.setPassword("");
            submit.setPortNumber(3306);
            submit.setDatabaseName("private_musik");
            
            Connection koneksi=submit.getConnection();
            
            ResultSet rs = koneksi.prepareStatement("select Id_Pengajar,"+
                    "Nama_Pengajar,Jenis_Kelamin,Alamat,Id_Alat_Musik from pengajar where Id_Pengajar='"+UserSession.getUserLogin()+"'").executeQuery();
                 if(rs.next()){
                     txtidpengajar.setText(rs.getString(1));
                     txtnamapengajar.setText(rs.getString(2));
                     txtkelaminpengajar.setSelectedItem(rs.getString(3));
                     txtalamatpengajar.setText(rs.getString(4));
                     txtalatmusikpengajar.setSelectedIndex(rs.getInt(5));
                }
        }catch(Exception e){
            System.out.println(e);
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mize;
    private javax.swing.JLabel tutup;
    private javax.swing.JTextArea txtalamatpengajar;
    private javax.swing.JComboBox txtalatmusikpengajar;
    private javax.swing.JTextField txtidpengajar;
    private javax.swing.JComboBox txtkelaminpengajar;
    private javax.swing.JTextField txtnamapengajar;
    // End of variables declaration//GEN-END:variables
}
