/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesar_privatemusik;
import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author Ronaldo
 */
public class EditProfileSiswa extends javax.swing.JFrame {
    int mousePX;
    int mousePY;
    /**
     * Creates new form EditProfileSiswa
     */
    public EditProfileSiswa() {
        initComponents();
        setLocationRelativeTo(null);

        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tutup = new javax.swing.JLabel();
        mize = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtkelaminsiswa = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtidsiswa = new javax.swing.JTextField();
        txtnamasiswa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamatsiswa = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        tutup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tutup.setForeground(new java.awt.Color(255, 255, 255));
        tutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonExit.png"))); // NOI18N
        tutup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tutup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutupMouseClicked(evt);
            }
        });
        getContentPane().add(tutup);
        tutup.setBounds(570, 0, 20, 30);

        mize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mize.setForeground(new java.awt.Color(255, 255, 255));
        mize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonMinimize.png"))); // NOI18N
        mize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mizeMouseClicked(evt);
            }
        });
        getContentPane().add(mize);
        mize.setBounds(550, 0, 20, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonUpdate.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 320, 100, 30);

        jLabel6.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 55, 153));
        jLabel6.setText("Jenis Kelamin");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 180, 130, 23);

        txtkelaminsiswa.setBackground(new java.awt.Color(204, 204, 204));
        txtkelaminsiswa.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 11)); // NOI18N
        txtkelaminsiswa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-Laki", "Perempuan" }));
        txtkelaminsiswa.setBorder(null);
        txtkelaminsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkelaminsiswaActionPerformed(evt);
            }
        });
        getContentPane().add(txtkelaminsiswa);
        txtkelaminsiswa.setBounds(240, 180, 91, 30);

        jLabel3.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 55, 153));
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 140, 60, 20);

        txtidsiswa.setEditable(false);
        txtidsiswa.setBackground(new java.awt.Color(204, 204, 204));
        txtidsiswa.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 18)); // NOI18N
        txtidsiswa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidsiswa.setBorder(null);
        txtidsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidsiswaActionPerformed(evt);
            }
        });
        getContentPane().add(txtidsiswa);
        txtidsiswa.setBounds(240, 100, 220, 30);

        txtnamasiswa.setBackground(new java.awt.Color(204, 204, 204));
        txtnamasiswa.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 18)); // NOI18N
        txtnamasiswa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnamasiswa.setBorder(null);
        txtnamasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamasiswaActionPerformed(evt);
            }
        });
        txtnamasiswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnamasiswaKeyTyped(evt);
            }
        });
        getContentPane().add(txtnamasiswa);
        txtnamasiswa.setBounds(240, 140, 220, 30);

        txtalamatsiswa.setBackground(new java.awt.Color(204, 204, 204));
        txtalamatsiswa.setColumns(20);
        txtalamatsiswa.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtalamatsiswa.setRows(5);
        txtalamatsiswa.setBorder(null);
        jScrollPane1.setViewportView(txtalamatsiswa);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 220, 300, 60);

        jLabel7.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 55, 153));
        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 220, 80, 23);

        jLabel4.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 55, 153));
        jLabel4.setText("Id Siswa");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 100, 130, 20);

        jLabel8.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonBack.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 320, 100, 30);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundEditProfile_1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamasiswaActionPerformed

    private void txtidsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidsiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidsiswaActionPerformed

    private void txtkelaminsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkelaminsiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkelaminsiswaActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        dispose();
        new FormSiswa().setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        String nama=txtnamasiswa.getText();
        String alamat=txtalamatsiswa.getText();
        if(nama.equals("")||alamat.equals("")){
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!");
        }else{
            try{
                MysqlDataSource submit = new MysqlDataSource();
                submit.setServerName("localhost");
                submit.setUser("root");
                submit.setPassword("");
                submit.setPortNumber(3306);
                submit.setDatabaseName("private_musik");

                Connection koneksi=submit.getConnection();

                koneksi.prepareStatement(
                    "update siswa set Nama_Siswa = '"+txtnamasiswa.getText()+
                    "', Jenis_Kelamin = '"+txtkelaminsiswa.getSelectedItem()+
                    "', Alamat = '"+txtalamatsiswa.getText()+
                    "'where Id_Siswa = '"+UserSession.getUserLogin()+"' ").execute();

                JOptionPane.showMessageDialog(null, "Profil berhasil diperbaharui!");
                dispose();
                new FormSiswa().setVisible(true);
            }catch(Exception e){
                System.out.println(e);

            }
        }        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void mizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mizeMouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_mizeMouseClicked

    private void tutupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutupMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tutupMouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        // TODO add your handling code here:
        int koordinatX = evt.getXOnScreen();
        int koordinatY = evt.getYOnScreen();

        this.setLocation(koordinatX-mousePX, koordinatY-mousePY);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void txtnamasiswaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamasiswaKeyTyped
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtnamasiswaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfileSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfileSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfileSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfileSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProfileSiswa().setVisible(true);
            }
        });
    }
    
    public void tampil() {
        try{
            MysqlDataSource submit = new MysqlDataSource();
            submit.setServerName("localhost");
            submit.setUser("root");
            submit.setPassword("");
            submit.setPortNumber(3306);
            submit.setDatabaseName("private_musik");
            
            Connection koneksi=submit.getConnection();
            
            ResultSet rs = koneksi.prepareStatement("select Id_Siswa,"+
                    "Nama_Siswa,Jenis_Kelamin,Alamat from siswa where Id_Siswa='"+UserSession.getUserLogin()+"'").executeQuery();
                 if(rs.next()){
                     txtidsiswa.setText(rs.getString(1));
                     txtnamasiswa.setText(rs.getString(2));
                     txtkelaminsiswa.setSelectedItem(rs.getString(3));
                     txtalamatsiswa.setText(rs.getString(4));
                }
        }catch(Exception e){
            System.out.println(e);
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mize;
    private javax.swing.JLabel tutup;
    private javax.swing.JTextArea txtalamatsiswa;
    private javax.swing.JTextField txtidsiswa;
    private javax.swing.JComboBox txtkelaminsiswa;
    private javax.swing.JTextField txtnamasiswa;
    // End of variables declaration//GEN-END:variables
}
