/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesar_privatemusik;

import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronaldo
 */
public class GantiPasswordPengajar extends javax.swing.JFrame {
    int mousePX;
    int mousePY;
    /**
     * Creates new form GantiPasswordPengajar
     */
    public GantiPasswordPengajar() {
        initComponents();
        setLocationRelativeTo(null);
        
        try{
            MysqlDataSource submit = new MysqlDataSource();
            submit.setServerName("localhost");
            submit.setUser("root");
            submit.setPassword("");
            submit.setPortNumber(3306);
            submit.setDatabaseName("private_musik");
            
            Connection koneksi = submit.getConnection();
            
            ResultSet rs = koneksi.prepareStatement("select Username,Password from pengajar where Id_Pengajar='"+UserSession.getUserLogin()+"'").executeQuery();
            while(rs.next()){
                txtuserpengajar.setText(rs.getString(1));
                txtpasspengajar.setText(rs.getString(2));
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        mize = new javax.swing.JLabel();
        tutup = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtuserpengajar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtpasspengajar = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(300, 200));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonSave.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 160, 100, 30);

        mize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mize.setForeground(new java.awt.Color(255, 255, 255));
        mize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonMinimize.png"))); // NOI18N
        mize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mizeMouseClicked(evt);
            }
        });
        getContentPane().add(mize);
        mize.setBounds(250, 0, 20, 30);

        tutup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tutup.setForeground(new java.awt.Color(255, 255, 255));
        tutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonExit.png"))); // NOI18N
        tutup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tutup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutupMouseClicked(evt);
            }
        });
        getContentPane().add(tutup);
        tutup.setBounds(270, 0, 20, 30);

        jLabel7.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonBack.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 160, 100, 30);

        jLabel5.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(217, 30, 24));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Username");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 30, 220, 20);

        txtuserpengajar.setBackground(new java.awt.Color(52, 73, 94));
        txtuserpengajar.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        txtuserpengajar.setForeground(new java.awt.Color(255, 255, 255));
        txtuserpengajar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtuserpengajar.setBorder(null);
        txtuserpengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserpengajarActionPerformed(evt);
            }
        });
        getContentPane().add(txtuserpengajar);
        txtuserpengajar.setBounds(40, 60, 220, 30);

        jLabel8.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(217, 30, 24));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 90, 220, 20);

        txtpasspengajar.setBackground(new java.awt.Color(52, 73, 94));
        txtpasspengajar.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        txtpasspengajar.setForeground(new java.awt.Color(255, 255, 255));
        txtpasspengajar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpasspengajar.setBorder(null);
        txtpasspengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasspengajarActionPerformed(evt);
            }
        });
        getContentPane().add(txtpasspengajar);
        txtpasspengajar.setBounds(40, 120, 220, 30);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 300, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundGantiPassword.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 300, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtuserpengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserpengajarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserpengajarActionPerformed

    private void txtpasspengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasspengajarActionPerformed
        // TODO add your handling code here:
        String user=txtuserpengajar.getText();
        String pass=txtpasspengajar.getText();
        if(user.equals("")||pass.equals("")){
            JOptionPane.showMessageDialog(null, "Username & Password tidak boleh kosong!");
        }else{
            gantipassword();
        }
    }//GEN-LAST:event_txtpasspengajarActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        dispose();
        new FormPengajar().setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void tutupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutupMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tutupMouseClicked

    private void mizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mizeMouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_mizeMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        String user=txtuserpengajar.getText();
        String pass=txtpasspengajar.getText();
        if(user.equals("")||pass.equals("")){
            JOptionPane.showMessageDialog(null, "Username & Password tidak boleh kosong!");
        }else{
            gantipassword();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
        // TODO add your handling code here:
        int koordinatX = evt.getXOnScreen();
        int koordinatY = evt.getYOnScreen();

        this.setLocation(koordinatX-mousePX, koordinatY-mousePY);
    }//GEN-LAST:event_jLabel3MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GantiPasswordPengajar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GantiPasswordPengajar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GantiPasswordPengajar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GantiPasswordPengajar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GantiPasswordPengajar().setVisible(true);
            }
        });
    }

    private void gantipassword(){
        try{
            MysqlDataSource submit = new MysqlDataSource();
            submit.setServerName("localhost");
            submit.setUser("root");
            submit.setPassword("");
            submit.setPortNumber(3306);
            submit.setDatabaseName("private_musik");

            Connection koneksi=submit.getConnection();

            koneksi.prepareStatement(
                "update pengajar set Username = '"+txtuserpengajar.getText()+
                "', Password = '"+txtpasspengajar.getText()+
                "' where Id_Pengajar='"+UserSession.getUserLogin()+"' ").execute();

            txtuserpengajar.setText("");
            txtpasspengajar.setText("");
            JOptionPane.showMessageDialog(null, "Username & Password telah tersimpan!");
            dispose();
            new LoginPengajar().setVisible(true);
        }catch(Exception e){
            System.out.println(e);

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel mize;
    private javax.swing.JLabel tutup;
    private javax.swing.JPasswordField txtpasspengajar;
    private javax.swing.JTextField txtuserpengajar;
    // End of variables declaration//GEN-END:variables

}
