/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesar_privatemusik;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.Statement;
import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ronaldo
 */
public class JadwalAdmin extends javax.swing.JFrame {
    DefaultTableModel tabelmodel;
    int mousePX;
    int mousePY;
    /**
     * Creates new form JadwalAdmin
     */
    public JadwalAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        
        String[] judul={"Id Jadwal","Hari","Jam","Id Pengajar","Id Siswa","Id Alat Musik","Id Ruangan"};
        tabelmodel = new DefaultTableModel(null, judul);
        tabeljadwaladmin.setModel(tabelmodel);
        
        autonumber();
        tampil();
        Beranda t = new Beranda();
        jLabel12.setText(t.totalsiswa);
        jLabel13.setText(t.totalpengajar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cariidpengajar = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cariidsiswa = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        carialatmusik = new javax.swing.JComboBox();
        carihari = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtidjadwal = new javax.swing.JTextField();
        txthariadmin = new javax.swing.JComboBox();
        txtjamadmin = new javax.swing.JComboBox();
        txtidpengajar = new javax.swing.JTextField();
        txtidsiswa = new javax.swing.JTextField();
        txtalatmusik = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        backlogin = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtruangan = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeljadwaladmin = new javax.swing.JTable();
        mize = new javax.swing.JLabel();
        tutup1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        cariidpengajar.setBackground(new java.awt.Color(204, 204, 204));
        cariidpengajar.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 14)); // NOI18N
        cariidpengajar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cariidpengajar.setBorder(null);
        cariidpengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariidpengajarActionPerformed(evt);
            }
        });
        getContentPane().add(cariidpengajar);
        cariidpengajar.setBounds(260, 560, 90, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Cari Id Pengajar");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(270, 550, 70, 10);

        cariidsiswa.setBackground(new java.awt.Color(204, 204, 204));
        cariidsiswa.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 14)); // NOI18N
        cariidsiswa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cariidsiswa.setBorder(null);
        cariidsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariidsiswaActionPerformed(evt);
            }
        });
        getContentPane().add(cariidsiswa);
        cariidsiswa.setBounds(360, 560, 90, 30);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonUpdate.png"))); // NOI18N
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17);
        jLabel17.setBounds(520, 270, 100, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonCari.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16);
        jLabel16.setBounds(680, 560, 100, 30);

        carialatmusik.setBackground(new java.awt.Color(204, 204, 204));
        carialatmusik.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 14)); // NOI18N
        carialatmusik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0. Gitar", "1. Piano", "2. Bass", "3. Drum", "4. Saxophone", "5. Biola" }));
        carialatmusik.setBorder(null);
        carialatmusik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carialatmusikActionPerformed(evt);
            }
        });
        getContentPane().add(carialatmusik);
        carialatmusik.setBounds(460, 560, 100, 30);

        carihari.setBackground(new java.awt.Color(204, 204, 204));
        carihari.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 14)); // NOI18N
        carihari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu" }));
        carihari.setBorder(null);
        carihari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carihariActionPerformed(evt);
            }
        });
        getContentPane().add(carihari);
        carihari.setBounds(570, 560, 100, 30);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(670, 160, 80, 30);

        jLabel7.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 55, 153));
        jLabel7.setText("Ruangan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 310, 150, 23);

        jLabel11.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(30, 55, 153));
        jLabel11.setText("Alat Musik");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(130, 270, 150, 23);

        jLabel6.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 55, 153));
        jLabel6.setText("Id Siswa");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 230, 150, 23);

        jLabel4.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 55, 153));
        jLabel4.setText("Id Pengajar");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 190, 150, 23);

        jLabel3.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 55, 153));
        jLabel3.setText("Jam");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 150, 150, 23);

        jLabel2.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 55, 153));
        jLabel2.setText("Hari");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 110, 150, 23);

        txtidjadwal.setEditable(false);
        txtidjadwal.setBackground(new java.awt.Color(204, 204, 204));
        txtidjadwal.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 14)); // NOI18N
        txtidjadwal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidjadwal.setBorder(null);
        txtidjadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidjadwalActionPerformed(evt);
            }
        });
        getContentPane().add(txtidjadwal);
        txtidjadwal.setBounds(300, 70, 200, 30);

        txthariadmin.setBackground(new java.awt.Color(204, 204, 204));
        txthariadmin.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 14)); // NOI18N
        txthariadmin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu" }));
        txthariadmin.setBorder(null);
        getContentPane().add(txthariadmin);
        txthariadmin.setBounds(300, 110, 200, 30);

        txtjamadmin.setBackground(new java.awt.Color(204, 204, 204));
        txtjamadmin.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 14)); // NOI18N
        txtjamadmin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "19:00:00" }));
        txtjamadmin.setBorder(null);
        txtjamadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjamadminActionPerformed(evt);
            }
        });
        getContentPane().add(txtjamadmin);
        txtjamadmin.setBounds(300, 150, 200, 30);

        txtidpengajar.setBackground(new java.awt.Color(204, 204, 204));
        txtidpengajar.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 14)); // NOI18N
        txtidpengajar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidpengajar.setBorder(null);
        txtidpengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpengajarActionPerformed(evt);
            }
        });
        getContentPane().add(txtidpengajar);
        txtidpengajar.setBounds(300, 190, 200, 30);

        txtidsiswa.setBackground(new java.awt.Color(204, 204, 204));
        txtidsiswa.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 14)); // NOI18N
        txtidsiswa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidsiswa.setBorder(null);
        txtidsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidsiswaActionPerformed(evt);
            }
        });
        getContentPane().add(txtidsiswa);
        txtidsiswa.setBounds(300, 230, 200, 30);

        txtalatmusik.setBackground(new java.awt.Color(204, 204, 204));
        txtalatmusik.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 14)); // NOI18N
        txtalatmusik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0. Gitar", "1. Piano", "2. Bass", "3. Drum", "4. Saxophone", "5. Biola" }));
        txtalatmusik.setBorder(null);
        txtalatmusik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalatmusikActionPerformed(evt);
            }
        });
        getContentPane().add(txtalatmusik);
        txtalatmusik.setBounds(300, 270, 200, 30);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(670, 130, 80, 30);

        jLabel1.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 55, 153));
        jLabel1.setText("Id Jadwal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 70, 150, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonSave.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(520, 230, 100, 30);

        backlogin.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 14)); // NOI18N
        backlogin.setForeground(new java.awt.Color(255, 255, 255));
        backlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonBack.png"))); // NOI18N
        backlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backloginMouseClicked(evt);
            }
        });
        getContentPane().add(backlogin);
        backlogin.setBounds(20, 560, 100, 30);

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(30, 55, 153));
        jLabel14.setText("Jumlah Pengajar   :");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(530, 160, 110, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Cari Id Siswa");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(370, 550, 70, 10);

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(30, 55, 153));
        jLabel15.setText("Jumlah Siswa         :");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(530, 130, 130, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonHapus.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(520, 310, 100, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonReset.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(120, 560, 100, 30);

        txtruangan.setBackground(new java.awt.Color(204, 204, 204));
        txtruangan.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 14)); // NOI18N
        txtruangan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "B001", "L001", "D001", "G001", "K001", "S001" }));
        txtruangan.setBorder(null);
        txtruangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtruanganActionPerformed(evt);
            }
        });
        getContentPane().add(txtruangan);
        txtruangan.setBounds(300, 310, 200, 30);

        tabeljadwaladmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeljadwaladmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeljadwaladminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeljadwaladmin);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 360, 760, 170);

        mize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mize.setForeground(new java.awt.Color(255, 255, 255));
        mize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonMinimize.png"))); // NOI18N
        mize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mizeMouseClicked(evt);
            }
        });
        getContentPane().add(mize);
        mize.setBounds(750, 10, 20, 30);

        tutup1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tutup1.setForeground(new java.awt.Color(255, 255, 255));
        tutup1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonExit.png"))); // NOI18N
        tutup1.setText("X");
        tutup1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tutup1.setPreferredSize(new java.awt.Dimension(20, 20));
        tutup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutup1tutupMouseClicked(evt);
            }
        });
        getContentPane().add(tutup1);
        tutup1.setBounds(770, 10, 20, 30);

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel5MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 800, 40);

        jlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundUpdate.png"))); // NOI18N
        getContentPane().add(jlabel);
        jlabel.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        String id= txtidpengajar.getText();
        String siswa = txtidsiswa.getText();
        if(siswa.equals("")||id.equals("")){
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!");
        }else{
            try{
                MysqlDataSource submit = new MysqlDataSource();
                submit.setServerName("localhost");
                submit.setUser("root");
                submit.setPassword("");
                submit.setPortNumber(3306);
                submit.setDatabaseName("private_musik");

                Connection koneksi = submit.getConnection();

                ResultSet rs = koneksi.prepareStatement("select hari,Id_Siswa from jadwal "+
                        "where Id_Siswa='"+txtidsiswa.getText()+"' and hari='"+txthariadmin.getSelectedItem()+"'").executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Jadwal siswa ada yang bertabrakan!");
                }else{
                    try{                    
                        koneksi.prepareStatement("insert into jadwal values ('"+
                            txtidjadwal.getText()+"','"+
                            txthariadmin.getSelectedItem()+"','"+
                            txtjamadmin.getSelectedItem()+"','"+
                            txtidpengajar.getText()+"','"+
                            txtidsiswa.getText()+"','"+                
                            txtalatmusik.getSelectedIndex()+"','"+
                            txtruangan.getSelectedItem()+"')").execute();

                        autonumber();
                        tampil();
                        txtalatmusik.setSelectedItem("Gitar");
                        txtidpengajar.setText("");
                        txtidsiswa.setText("");
                        txthariadmin.setSelectedItem("Senin");
                        txtjamadmin.setSelectedItem("19:00:00");
                        txtruangan.setSelectedItem("B001");
                        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                    }catch(Exception e){
                        System.out.println(e);

                    }
                }
            }catch(Exception e){
                System.out.println(e);
            }
        }                  
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        int jawab = JOptionPane.showConfirmDialog(null, "Apakah anda Ingin Menghapus?");
        
        switch(jawab){
            case JOptionPane.YES_OPTION:
                if(tabeljadwaladmin.getSelectedColumnCount()!=-1){
                    try{
                        MysqlDataSource submit = new MysqlDataSource();
                        submit.setServerName("localhost");
                        submit.setUser("root");
                        submit.setPassword("");
                        submit.setPortNumber(3306);
                        submit.setDatabaseName("private_musik");

                        Connection koneksi=submit.getConnection();

                        koneksi.prepareStatement(
                            "DELETE FROM jadwal WHERE Id_Jadwal ='"+
                            tabeljadwaladmin.getValueAt(tabeljadwaladmin.getSelectedRow(), 0).toString()+
                            "' ").executeUpdate();

                        autonumber();
                        tampil();
                    }catch(Exception e){
                        System.out.println(e);
                    }
                }
                break;
            case JOptionPane.NO_OPTION:
                break;
            case JOptionPane.CANCEL_OPTION:
                break;
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseDragged
        // TODO add your handling code here:
        int koordinatX = evt.getXOnScreen();
        int koordinatY = evt.getYOnScreen();

        this.setLocation(koordinatX-mousePX, koordinatY-mousePY);
    }//GEN-LAST:event_jLabel5MouseDragged

    private void mizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mizeMouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_mizeMouseClicked

    private void tutup1tutupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutup1tutupMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tutup1tutupMouseClicked

    private void backloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backloginMouseClicked
        // TODO add your handling code here:
        dispose();
        new FormAdmin().setVisible(true);
    }//GEN-LAST:event_backloginMouseClicked

    private void txtidjadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidjadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidjadwalActionPerformed

    private void txtjamadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjamadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjamadminActionPerformed

    private void txtidpengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpengajarActionPerformed
        // TODO add your handling code here:
        try{
            MysqlDataSource submit = new MysqlDataSource();
            submit.setServerName("localhost");
            submit.setUser("root");
            submit.setPassword("");
            submit.setPortNumber(3306);
            submit.setDatabaseName("private_musik");
            
            Connection koneksi = submit.getConnection();
            
            ResultSet rs = koneksi.prepareStatement("select Id_Alat_Musik from pengajar"+
                    " where Id_Pengajar='"+txtidpengajar.getText()+"'").executeQuery();
                if(rs.next()){
                    txtalatmusik.setSelectedIndex(Integer.parseInt(rs.getString(1)));
                }else {
                    JOptionPane.showMessageDialog(null, "Pengajar Tidak Terdaftar");
                }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_txtidpengajarActionPerformed

    private void txtidsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidsiswaActionPerformed
        // TODO add your handling code here:
        try{
            MysqlDataSource submit = new MysqlDataSource();
            submit.setServerName("localhost");
            submit.setUser("root");
            submit.setPassword("");
            submit.setPortNumber(3306);
            submit.setDatabaseName("private_musik");
            
            Connection koneksi = submit.getConnection();
            
            ResultSet rs = koneksi.prepareStatement("select Id_Siswa from siswa"+
                    " where Id_Siswa='"+txtidsiswa.getText()+"'").executeQuery();
                if(rs.next()){
                    
                }else {
                    JOptionPane.showMessageDialog(null, "Siswa Tidak Terdaftar");
                }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_txtidsiswaActionPerformed

    private void tabeljadwaladminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeljadwaladminMouseClicked
        // TODO add your handling code here:
        int baris = tabeljadwaladmin.getSelectedRow();
        String idjadwal = (String)tabelmodel.getValueAt(baris, 0);
        String hari = (String)tabelmodel.getValueAt(baris, 1);
        String jam = (String)tabelmodel.getValueAt(baris, 2);
        String idpengajar = (String)tabelmodel.getValueAt(baris, 3);
        String idsiswa = (String)tabelmodel.getValueAt(baris, 4);
        String alatmusik = (String)tabelmodel.getValueAt(baris, 5);
        String ruangan = (String)tabelmodel.getValueAt(baris, 6);
        int idalat = Integer.parseInt(alatmusik);
        
        txtidjadwal.setText(idjadwal);
        txthariadmin.setSelectedItem(hari);
        txtjamadmin.setSelectedItem(jam);
        txtidpengajar.setText(idpengajar);
        txtidsiswa.setText(idsiswa);
        txtalatmusik.setSelectedIndex(idalat);
        txtruangan.setSelectedItem(ruangan);
    }//GEN-LAST:event_tabeljadwaladminMouseClicked

    private void txtalatmusikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalatmusikActionPerformed
        // TODO add your handling code here:
        if(txtalatmusik.getSelectedIndex()==0){
            txtruangan.setSelectedItem("G001");
        }else if(txtalatmusik.getSelectedIndex()==1){
            txtruangan.setSelectedItem("K001");
        }else if(txtalatmusik.getSelectedIndex()==2){
            txtruangan.setSelectedItem("B001");
        }else if(txtalatmusik.getSelectedIndex()==3){
            txtruangan.setSelectedItem("D001");
        }else if(txtalatmusik.getSelectedIndex()==4){
            txtruangan.setSelectedItem("S001");
        }else if(txtalatmusik.getSelectedIndex()==5){
            txtruangan.setSelectedItem("L001");
        }
    }//GEN-LAST:event_txtalatmusikActionPerformed

    private void txtruanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtruanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtruanganActionPerformed

    private void carialatmusikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carialatmusikActionPerformed
        // TODO add your handling code here:
        int baris = tabelmodel.getRowCount();
        for(int i=1;i<=baris;i++){
            tabelmodel.removeRow(0);
        }
        try{
            MysqlDataSource submit = new MysqlDataSource();
            submit.setServerName("localhost");
            submit.setUser("root");
            submit.setPassword("");
            submit.setPortNumber(3306);
            submit.setDatabaseName("private_musik");
            
            Connection koneksi = submit.getConnection();
            
            ResultSet rs = koneksi.prepareStatement("select * from jadwal where Id_Alat_Musik='"+carialatmusik.getSelectedIndex()+"'").executeQuery();
                while(rs.next()){
                    tabelmodel.addRow(new String[]{
                        rs.getString(1),
                        rs.getString(2),
                        rs.getString(3),
                        rs.getString(4),
                        rs.getString(5),
                        rs.getString(6),
                        rs.getString(7)}
                    );
                }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_carialatmusikActionPerformed

    private void carihariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carihariActionPerformed
        // TODO add your handling code here:
        int baris = tabelmodel.getRowCount();
        for(int i=1;i<=baris;i++){
            tabelmodel.removeRow(0);
        }
        try{
            MysqlDataSource submit = new MysqlDataSource();
            submit.setServerName("localhost");
            submit.setUser("root");
            submit.setPassword("");
            submit.setPortNumber(3306);
            submit.setDatabaseName("private_musik");
            
            Connection koneksi = submit.getConnection();
            
            ResultSet rs = koneksi.prepareStatement("select * from jadwal where Hari='"+carihari.getSelectedItem()+"'").executeQuery();
                while(rs.next()){
                    tabelmodel.addRow(new String[]{
                        rs.getString(1),
                        rs.getString(2),
                        rs.getString(3),
                        rs.getString(4),
                        rs.getString(5),
                        rs.getString(6),
                        rs.getString(7)}
                    );
                }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_carihariActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        tampil();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        int baris = tabelmodel.getRowCount();
        for(int i=1;i<=baris;i++){
            tabelmodel.removeRow(0);
        }
        try{
            MysqlDataSource submit = new MysqlDataSource();
            submit.setServerName("localhost");
            submit.setUser("root");
            submit.setPassword("");
            submit.setPortNumber(3306);
            submit.setDatabaseName("private_musik");
            
            Connection koneksi = submit.getConnection();
            
            ResultSet rs = koneksi.prepareStatement("select * from jadwal where "+
                    "Id_Alat_Musik='"+carialatmusik.getSelectedIndex()+"' and "+
                    "Hari='"+carihari.getSelectedItem()+"'").executeQuery();
                while(rs.next()){
                    tabelmodel.addRow(new String[]{
                        rs.getString(1),
                        rs.getString(2),
                        rs.getString(3),
                        rs.getString(4),
                        rs.getString(5),
                        rs.getString(6),
                        rs.getString(7)}
                    );
                }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        String pengajar=txtidpengajar.getText();
        String siswa=txtidsiswa.getText();
        if(pengajar.equals("")||siswa.equals("")){
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!");
        }else{
            try{
                MysqlDataSource submit = new MysqlDataSource();
                submit.setServerName("localhost");
                submit.setUser("root");
                submit.setPassword("");
                submit.setPortNumber(3306);
                submit.setDatabaseName("private_musik");

                Connection koneksi=submit.getConnection();

                koneksi.prepareStatement(
                    "update jadwal set hari = '"+txthariadmin.getSelectedItem()+
                    "', jam = '"+txtjamadmin.getSelectedItem()+                        
                    "', Id_Pengajar = '"+txtidpengajar.getText()+
                    "', Id_Siswa = '"+txtidsiswa.getText()+                        
                    "', Id_Alat_Musik='"+txtalatmusik.getSelectedIndex()+
                    "' where Id_Jadwal='"+txtidjadwal.getText()+"' ").execute();

                tampil();
                JOptionPane.showMessageDialog(null, "Data berhasil diperbaharui!");
                txthariadmin.setSelectedItem("Senin");
                txtjamadmin.setSelectedItem("19:00:00");
                txtidsiswa.setText("");
                txtalatmusik.setSelectedIndex(0);
                txtidpengajar.setText("");                
            }catch(Exception e){
                System.out.println(e);

            }   
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void cariidsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariidsiswaActionPerformed
        // TODO add your handling code here:
        int baris = tabelmodel.getRowCount();
        for(int i=1;i<=baris;i++){
            tabelmodel.removeRow(0);
        }
        try{
            MysqlDataSource submit = new MysqlDataSource();
            submit.setServerName("localhost");
            submit.setUser("root");
            submit.setPassword("");
            submit.setPortNumber(3306);
            submit.setDatabaseName("private_musik");
            
            Connection koneksi = submit.getConnection();
            
            ResultSet rs = koneksi.prepareStatement("select * from jadwal where "+
                    "Id_Siswa='"+cariidsiswa.getText()+"'").executeQuery();
                while(rs.next()){
                    tabelmodel.addRow(new String[]{
                        rs.getString(1),
                        rs.getString(2),
                        rs.getString(3),
                        rs.getString(4),
                        rs.getString(5),
                        rs.getString(6),
                        rs.getString(7)}
                    );
                }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_cariidsiswaActionPerformed

    private void cariidpengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariidpengajarActionPerformed
        // TODO add your handling code here:
        int baris = tabelmodel.getRowCount();
        for(int i=1;i<=baris;i++){
            tabelmodel.removeRow(0);
        }
        try{
            MysqlDataSource submit = new MysqlDataSource();
            submit.setServerName("localhost");
            submit.setUser("root");
            submit.setPassword("");
            submit.setPortNumber(3306);
            submit.setDatabaseName("private_musik");
            
            Connection koneksi = submit.getConnection();
            
            ResultSet rs = koneksi.prepareStatement("select * from jadwal where "+
                    "Id_Pengajar='"+cariidpengajar.getText()+"'").executeQuery();
                while(rs.next()){
                    tabelmodel.addRow(new String[]{
                        rs.getString(1),
                        rs.getString(2),
                        rs.getString(3),
                        rs.getString(4),
                        rs.getString(5),
                        rs.getString(6),
                        rs.getString(7)}
                    );
                }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_cariidpengajarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JadwalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JadwalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JadwalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JadwalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JadwalAdmin().setVisible(true);
            }
        });
    }
    
    private void tampil(){
        int baris = tabelmodel.getRowCount();
        for(int i=1;i<=baris;i++){
            tabelmodel.removeRow(0);
        }
        try{
            MysqlDataSource submit = new MysqlDataSource();
            submit.setServerName("localhost");
            submit.setUser("root");
            submit.setPassword("");
            submit.setPortNumber(3306);
            submit.setDatabaseName("private_musik");
            
            Connection koneksi = submit.getConnection();
            
            ResultSet rs = koneksi.prepareStatement("select * from jadwal").executeQuery();
                while(rs.next()){
                    tabelmodel.addRow(new String[]{
                        rs.getString(1),
                        rs.getString(2),
                        rs.getString(3),
                        rs.getString(4),
                        rs.getString(5),
                        rs.getString(6),
                        rs.getString(7)}
                    );
                }
        }catch(Exception e){
            System.out.println(e);
        }
    }

    private void autonumber(){
        try{
            MysqlDataSource submit = new MysqlDataSource();
            submit.setServerName("localhost");
            submit.setUser("root");
            submit.setPassword("");
            submit.setPortNumber(3306);
            submit.setDatabaseName("private_musik");
            
            Connection koneksi=submit.getConnection();
            Statement state = koneksi.createStatement();
            String query = "SELECT MAX(Right(Id_Jadwal,2)) as no FROM jadwal";
            
            ResultSet rs = state.executeQuery(query);
            while(rs.next()){
                if(rs.last()){
                    rs.last();
                    int auto_id = rs.getInt(1)+1;
                    String no = String.valueOf(auto_id);
                    int noLong = no.length();
                                for(int a=0;a<3-noLong;a++){
                                    no = "0" + no;
                                }
                    txtidjadwal.setText(no);
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "error \n"+ e.toString(),"Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backlogin;
    private javax.swing.JComboBox carialatmusik;
    private javax.swing.JComboBox carihari;
    private javax.swing.JTextField cariidpengajar;
    private javax.swing.JTextField cariidsiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel mize;
    private javax.swing.JTable tabeljadwaladmin;
    private javax.swing.JLabel tutup1;
    private javax.swing.JComboBox txtalatmusik;
    private javax.swing.JComboBox txthariadmin;
    private javax.swing.JTextField txtidjadwal;
    private javax.swing.JTextField txtidpengajar;
    private javax.swing.JTextField txtidsiswa;
    private javax.swing.JComboBox txtjamadmin;
    private javax.swing.JComboBox txtruangan;
    // End of variables declaration//GEN-END:variables
}
