/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesar_privatemusik;
import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronaldo
 */
public class LoginSiswa extends javax.swing.JFrame {
    int mousePX;
    int mousePY;
    /**
     * Creates new form LoginSiswa
     */
    public LoginSiswa() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tutup1 = new javax.swing.JLabel();
        mize = new javax.swing.JLabel();
        usernamesiswa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passwordsiswa = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        loginsiswa = new javax.swing.JButton();
        backloginsiswa = new javax.swing.JLabel();
        resetloginsiswa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        tutup1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tutup1.setForeground(new java.awt.Color(255, 255, 255));
        tutup1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonExit.png"))); // NOI18N
        tutup1.setText("X");
        tutup1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tutup1.setPreferredSize(new java.awt.Dimension(20, 20));
        tutup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutupMouseClicked(evt);
            }
        });
        getContentPane().add(tutup1);
        tutup1.setBounds(570, 0, 20, 30);

        mize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mize.setForeground(new java.awt.Color(255, 255, 255));
        mize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonMinimize.png"))); // NOI18N
        mize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mizeMouseClicked(evt);
            }
        });
        getContentPane().add(mize);
        mize.setBounds(550, 0, 20, 30);

        usernamesiswa.setBackground(new java.awt.Color(52, 73, 94));
        usernamesiswa.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 24)); // NOI18N
        usernamesiswa.setForeground(new java.awt.Color(255, 255, 255));
        usernamesiswa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernamesiswa.setBorder(null);
        usernamesiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamesiswaActionPerformed(evt);
            }
        });
        getContentPane().add(usernamesiswa);
        usernamesiswa.setBounds(170, 130, 260, 50);

        jLabel5.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("username");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 110, 60, 14);

        jLabel4.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 167, 240));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Login Siswa");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 60, 320, 45);

        passwordsiswa.setBackground(new java.awt.Color(52, 73, 94));
        passwordsiswa.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        passwordsiswa.setForeground(new java.awt.Color(255, 255, 255));
        passwordsiswa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordsiswa.setBorder(null);
        passwordsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordsiswaActionPerformed(evt);
            }
        });
        getContentPane().add(passwordsiswa);
        passwordsiswa.setBounds(170, 200, 260, 50);

        jLabel6.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 180, 60, 14);

        loginsiswa.setBackground(new java.awt.Color(249, 105, 14));
        loginsiswa.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 24)); // NOI18N
        loginsiswa.setForeground(new java.awt.Color(255, 255, 255));
        loginsiswa.setText("Sign in");
        loginsiswa.setBorder(null);
        loginsiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginsiswaActionPerformed(evt);
            }
        });
        getContentPane().add(loginsiswa);
        loginsiswa.setBounds(170, 260, 260, 50);

        backloginsiswa.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 14)); // NOI18N
        backloginsiswa.setForeground(new java.awt.Color(255, 255, 255));
        backloginsiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonBack.png"))); // NOI18N
        backloginsiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backloginsiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backloginsiswaMouseClicked(evt);
            }
        });
        getContentPane().add(backloginsiswa);
        backloginsiswa.setBounds(170, 320, 100, 30);

        resetloginsiswa.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 14)); // NOI18N
        resetloginsiswa.setForeground(new java.awt.Color(255, 255, 255));
        resetloginsiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resetloginsiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonReset.png"))); // NOI18N
        resetloginsiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetloginsiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetloginsiswaMouseClicked(evt);
            }
        });
        getContentPane().add(resetloginsiswa);
        resetloginsiswa.setBounds(330, 320, 100, 30);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundLogin.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernamesiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamesiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamesiswaActionPerformed

    private void passwordsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordsiswaActionPerformed
        // TODO add your handling code here:
        loginsiswa();
    }//GEN-LAST:event_passwordsiswaActionPerformed

    private void loginsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginsiswaActionPerformed
        loginsiswa();
    }//GEN-LAST:event_loginsiswaActionPerformed

    private void backloginsiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backloginsiswaMouseClicked
        // TODO add your handling code here:
        dispose();
        new Beranda().setVisible(true);
    }//GEN-LAST:event_backloginsiswaMouseClicked

    private void resetloginsiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetloginsiswaMouseClicked
        // TODO add your handling code here:
        usernamesiswa.setText("");
        passwordsiswa.setText("");
    }//GEN-LAST:event_resetloginsiswaMouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        // TODO add your handling code here:
        int koordinatX = evt.getXOnScreen();
        int koordinatY = evt.getYOnScreen();

        this.setLocation(koordinatX-mousePX, koordinatY-mousePY);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void tutupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutupMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tutupMouseClicked

    private void mizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mizeMouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_mizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginSiswa().setVisible(true);
            }
        });
    }

    private void loginsiswa(){
        if(usernamesiswa.getText().equals("")||passwordsiswa.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Username & Password harus diisi!");
        }else{
            try{
            MysqlDataSource submit = new MysqlDataSource();
            submit.setServerName("localhost");
            submit.setUser("root");
            submit.setPassword("");
            submit.setPortNumber(3306);
            submit.setDatabaseName("private_musik");
            
            Connection koneksi = submit.getConnection();
            
            ResultSet rs = koneksi.prepareStatement("select Id_Siswa,Username,Password "+
                    "from siswa where Username='"+usernamesiswa.getText()+"'"+
                    " and Password='"+passwordsiswa.getText()+"'").executeQuery();
            if(rs.next()){
                UserSession.setUserLogin(rs.getString(1));
                dispose();
                new FormSiswa().setVisible(true);
            }else {
                JOptionPane.showMessageDialog(null, "Username dan Password Salah","Pesan Peringatan!",JOptionPane.WARNING_MESSAGE);
                usernamesiswa.setText("");
                passwordsiswa.setText("");
            }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backloginsiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loginsiswa;
    private javax.swing.JLabel mize;
    private javax.swing.JPasswordField passwordsiswa;
    private javax.swing.JLabel resetloginsiswa;
    private javax.swing.JLabel tutup1;
    private javax.swing.JTextField usernamesiswa;
    // End of variables declaration//GEN-END:variables
}
