/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesar_privatemusik;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfWriter;
import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ronaldo
 */
public class PendaftaranPengajar extends javax.swing.JFrame {
    int mousePX;
    int mousePY;
    /**
     * Creates new form PendaftaranPengajar
     */
    public PendaftaranPengajar() {
        initComponents();
        setLocationRelativeTo(null);

        autonumber();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tutup3 = new javax.swing.JLabel();
        mize = new javax.swing.JLabel();
        backpendpengajar = new javax.swing.JLabel();
        resetpendpengajar = new javax.swing.JLabel();
        submitpengajar = new javax.swing.JButton();
        txtalatmusikpengajar = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtpasspengajar = new javax.swing.JPasswordField();
        txtuserpengajar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidpengajar = new javax.swing.JTextField();
        txtnamapengajar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamatpengajar = new javax.swing.JTextArea();
        txtkelaminpengajar = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        tutup3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tutup3.setForeground(new java.awt.Color(255, 255, 255));
        tutup3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonExit.png"))); // NOI18N
        tutup3.setText("X");
        tutup3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tutup3.setPreferredSize(new java.awt.Dimension(20, 20));
        tutup3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutup3MouseClicked(evt);
            }
        });
        getContentPane().add(tutup3);
        tutup3.setBounds(770, 0, 20, 30);

        mize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mize.setForeground(new java.awt.Color(255, 255, 255));
        mize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonMinimize.png"))); // NOI18N
        mize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mizeMouseClicked(evt);
            }
        });
        getContentPane().add(mize);
        mize.setBounds(740, 0, 20, 30);

        backpendpengajar.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 14)); // NOI18N
        backpendpengajar.setForeground(new java.awt.Color(255, 255, 255));
        backpendpengajar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonBack.png"))); // NOI18N
        backpendpengajar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backpendpengajar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backpendpengajarMouseClicked(evt);
            }
        });
        getContentPane().add(backpendpengajar);
        backpendpengajar.setBounds(360, 510, 100, 30);

        resetpendpengajar.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 14)); // NOI18N
        resetpendpengajar.setForeground(new java.awt.Color(255, 255, 255));
        resetpendpengajar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resetpendpengajar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonReset.png"))); // NOI18N
        resetpendpengajar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetpendpengajar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetpendpengajarMouseClicked(evt);
            }
        });
        getContentPane().add(resetpendpengajar);
        resetpendpengajar.setBounds(480, 510, 100, 30);

        submitpengajar.setBackground(new java.awt.Color(249, 105, 14));
        submitpengajar.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 24)); // NOI18N
        submitpengajar.setForeground(new java.awt.Color(255, 255, 255));
        submitpengajar.setText("Submit");
        submitpengajar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitpengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitpengajarActionPerformed(evt);
            }
        });
        getContentPane().add(submitpengajar);
        submitpengajar.setBounds(360, 450, 220, 50);

        txtalatmusikpengajar.setBackground(new java.awt.Color(52, 73, 94));
        txtalatmusikpengajar.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 11)); // NOI18N
        txtalatmusikpengajar.setForeground(new java.awt.Color(255, 255, 255));
        txtalatmusikpengajar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0. Gitar", "1. Piano", "2. Bass", "3. Drum", "4. Saxophone", "5. Biola" }));
        txtalatmusikpengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalatmusikpengajarActionPerformed(evt);
            }
        });
        getContentPane().add(txtalatmusikpengajar);
        txtalatmusikpengajar.setBounds(360, 320, 90, 30);

        jLabel2.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jenis Alat Musik");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 320, 160, 23);

        txtpasspengajar.setBackground(new java.awt.Color(52, 73, 94));
        txtpasspengajar.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        txtpasspengajar.setForeground(new java.awt.Color(255, 255, 255));
        txtpasspengajar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpasspengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasspengajarActionPerformed(evt);
            }
        });
        getContentPane().add(txtpasspengajar);
        txtpasspengajar.setBounds(360, 400, 220, 30);

        txtuserpengajar.setBackground(new java.awt.Color(52, 73, 94));
        txtuserpengajar.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        txtuserpengajar.setForeground(new java.awt.Color(255, 255, 255));
        txtuserpengajar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtuserpengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserpengajarActionPerformed(evt);
            }
        });
        getContentPane().add(txtuserpengajar);
        txtuserpengajar.setBounds(360, 360, 220, 30);

        jLabel5.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 360, 120, 20);

        jLabel8.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 400, 130, 20);

        txtidpengajar.setEditable(false);
        txtidpengajar.setBackground(new java.awt.Color(52, 73, 94));
        txtidpengajar.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        txtidpengajar.setForeground(new java.awt.Color(255, 255, 255));
        txtidpengajar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidpengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpengajarActionPerformed(evt);
            }
        });
        getContentPane().add(txtidpengajar);
        txtidpengajar.setBounds(360, 130, 220, 30);

        txtnamapengajar.setBackground(new java.awt.Color(52, 73, 94));
        txtnamapengajar.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        txtnamapengajar.setForeground(new java.awt.Color(255, 255, 255));
        txtnamapengajar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnamapengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamapengajarActionPerformed(evt);
            }
        });
        txtnamapengajar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnamapengajarKeyTyped(evt);
            }
        });
        getContentPane().add(txtnamapengajar);
        txtnamapengajar.setBounds(360, 170, 220, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonCek.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(590, 360, 100, 30);

        jLabel7.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 250, 80, 23);

        jLabel3.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 170, 60, 20);

        txtalamatpengajar.setBackground(new java.awt.Color(52, 73, 94));
        txtalamatpengajar.setColumns(20);
        txtalamatpengajar.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtalamatpengajar.setForeground(new java.awt.Color(255, 255, 255));
        txtalamatpengajar.setRows(5);
        jScrollPane1.setViewportView(txtalamatpengajar);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(360, 250, 300, 60);

        txtkelaminpengajar.setBackground(new java.awt.Color(52, 73, 94));
        txtkelaminpengajar.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 11)); // NOI18N
        txtkelaminpengajar.setForeground(new java.awt.Color(255, 255, 255));
        txtkelaminpengajar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-Laki", "Perempuan" }));
        txtkelaminpengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkelaminpengajarActionPerformed(evt);
            }
        });
        getContentPane().add(txtkelaminpengajar);
        txtkelaminpengajar.setBounds(360, 210, 91, 30);

        jLabel6.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jenis Kelamin");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 210, 130, 23);

        jLabel4.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Id Pengajar");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 130, 130, 20);

        jLabel10.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(34, 167, 240));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Register Form");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(260, 50, 270, 45);

        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel9MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 800, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundPendaftaran.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamapengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamapengajarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamapengajarActionPerformed

    private void txtidpengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpengajarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpengajarActionPerformed

    private void txtkelaminpengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkelaminpengajarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkelaminpengajarActionPerformed

    private void txtuserpengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserpengajarActionPerformed
        // TODO add your handling code here:
        cekusername();
    }//GEN-LAST:event_txtuserpengajarActionPerformed

    private void txtpasspengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasspengajarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasspengajarActionPerformed

    private void txtalatmusikpengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalatmusikpengajarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalatmusikpengajarActionPerformed

    private void submitpengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitpengajarActionPerformed
        // TODO add your handling code here:
        String nama=txtnamapengajar.getText();
        String alamat=txtalamatpengajar.getText();
        String user=txtuserpengajar.getText();
        String pass=txtpasspengajar.getText();

        if(user.equals("")){
            JOptionPane.showMessageDialog(null, "Username kosong!");
        }else{
            try{
                MysqlDataSource submit = new MysqlDataSource();
                submit.setServerName("localhost");
                submit.setUser("root");
                submit.setPassword("");
                submit.setPortNumber(3306);
                submit.setDatabaseName("private_musik");

                Connection koneksi=submit.getConnection();

                ResultSet rs = koneksi.prepareStatement("select Username from pengajar where"+
                        " Username='"+txtuserpengajar.getText()+"'").executeQuery();                       
                    if(rs.next()){
                        JOptionPane.showMessageDialog(null, "Username sudah digunakan!");
                    }else{
                        if(nama.equals("")||alamat.equals("")||user.equals("")||pass.equals("")){
                            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!");
                        }else{
                            try {
                                // TODO add your handling code here:
                                Document document=new Document();
                                try {
                                    PdfWriter.getInstance(document,new FileOutputStream("Data_Pribadi_Pengajar_"+txtnamapengajar.getText()+".pdf"));
                                } catch (FileNotFoundException ex) {
                                    Logger.getLogger(UpdateDataSiswaAdmin.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                document.open();
                                Font font1=new Font(Font.FontFamily.TIMES_ROMAN,20);
                                Paragraph pm = new Paragraph("PRIVATE MUSIC",font1);
                                pm.setAlignment(Element.ALIGN_CENTER);
                                document.add(pm);
                                Paragraph h = new Paragraph("HORRY",font1);
                                h.setAlignment(Element.ALIGN_CENTER);
                                document.add(h);               
                                Font font2=new Font(Font.FontFamily.TIMES_ROMAN,8);
                                Paragraph jln = new Paragraph("Jl. Terusan Ryacudu, Desa WayHuwi Kecamatan Jati Agung\nKabupaten Lampung Selatan 35365, Lampung\nEmail:ronaldoblackviper@gmail.com , Phone : 089648033807",font2);
                                jln.setAlignment(Element.ALIGN_CENTER);
                                document.add(jln);
                                Paragraph para = new Paragraph("\n\n\nFormulir Pendaftaran Pengajar\n\n");
                                para.setAlignment(Element.ALIGN_CENTER);
                                document.add(para);
                                document.add(new Paragraph("Id Pengajar : "+txtidpengajar.getText())); 
                                document.add(new Paragraph("Nama : "+txtnamapengajar.getText())); 
                                document.add(new Paragraph("Jenis Kelamin : "+txtkelaminpengajar.getSelectedItem())); 
                                document.add(new Paragraph("Alamat : "+txtalamatpengajar.getText())); 
                                document.add(new Paragraph("Keahlian : "+txtalatmusikpengajar.getSelectedItem())); 
                                document.add(new Paragraph("Username : "+txtuserpengajar.getText())); 
                                document.add(new Paragraph("Password : "+txtpasspengajar.getText()+"\n\n"));
                                Paragraph d = new Paragraph("            Dengan ini saya menyatakan, mendaftarkan diri sebagai pengajar di HORRY Musik Lampung, dan saya akan mematuhi semua tata tertib dan peraturan yang berlaku di HORRY Musik Lampung\n\n\n\n");
                                d.setAlignment(Element.ALIGN_JUSTIFIED);
                                document.add(d);
                                Paragraph nyata = new Paragraph("Yang Menyatakan\n\n\n");
                                nyata.setAlignment(Element.ALIGN_RIGHT);
                                document.add(nyata);
                                Paragraph namasetuju = new Paragraph(txtnamapengajar.getText());
                                namasetuju.setAlignment(Element.ALIGN_RIGHT);
                                document.add(namasetuju);
                                document.close();
                            } catch (DocumentException ex) {
                                Logger.getLogger(UpdateDataSiswaAdmin.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            try{
                                koneksi.prepareStatement("insert into pengajar values ('"+
                                    txtidpengajar.getText()+"','"+
                                    txtnamapengajar.getText()+"','"+
                                    txtkelaminpengajar.getSelectedItem()+"','"+
                                    txtalamatpengajar.getText()+"','"+                    
                                    txtalatmusikpengajar.getSelectedIndex()+"','"+
                                    txtuserpengajar.getText()+"','"+
                                    txtpasspengajar.getText()+"')").execute();

                                txtalamatpengajar.setText("");
                                txtalatmusikpengajar.setSelectedItem("Gitar");
                                txtnamapengajar.setText("");
                                txtkelaminpengajar.setSelectedItem("Laki-Laki");
                                txtuserpengajar.setText("");
                                txtpasspengajar.setText("");
                                autonumber();
                                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                                dispose();
                                new Beranda().setVisible(true);
                            }catch(Exception e){
                                System.out.println(e);

                                JOptionPane.showMessageDialog(rootPane, "Data Sudah Diinputkan");
                            }
                        }
                    }                
            }catch(Exception e){
                System.out.println(e);

            }
        }                
    }//GEN-LAST:event_submitpengajarActionPerformed

    private void backpendpengajarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backpendpengajarMouseClicked
        // TODO add your handling code here:
        dispose();
        new Beranda().setVisible(true);
    }//GEN-LAST:event_backpendpengajarMouseClicked

    private void resetpendpengajarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetpendpengajarMouseClicked
        // TODO add your handling code here:
        txtalamatpengajar.setText("");
        txtalatmusikpengajar.setSelectedItem("Gitar");
        txtnamapengajar.setText("");
        txtkelaminpengajar.setSelectedItem("Laki_Laki");
        txtuserpengajar.setText("");
        txtpasspengajar.setText("");
    }//GEN-LAST:event_resetpendpengajarMouseClicked

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        // TODO add your handling code here:
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseDragged
        // TODO add your handling code here:
        int koordinatX = evt.getXOnScreen();
        int koordinatY = evt.getYOnScreen();

        this.setLocation(koordinatX-mousePX, koordinatY-mousePY);
    }//GEN-LAST:event_jLabel9MouseDragged

    private void mizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mizeMouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_mizeMouseClicked

    private void tutup3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutup3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tutup3MouseClicked

    private void txtnamapengajarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamapengajarKeyTyped
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtnamapengajarKeyTyped

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        cekusername();
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendaftaranPengajar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendaftaranPengajar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendaftaranPengajar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendaftaranPengajar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PendaftaranPengajar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backpendpengajar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mize;
    private javax.swing.JLabel resetpendpengajar;
    private javax.swing.JButton submitpengajar;
    private javax.swing.JLabel tutup3;
    private javax.swing.JTextArea txtalamatpengajar;
    private javax.swing.JComboBox txtalatmusikpengajar;
    private javax.swing.JTextField txtidpengajar;
    private javax.swing.JComboBox txtkelaminpengajar;
    private javax.swing.JTextField txtnamapengajar;
    private javax.swing.JPasswordField txtpasspengajar;
    private javax.swing.JTextField txtuserpengajar;
    // End of variables declaration//GEN-END:variables
    
    private void autonumber(){
        try{
            MysqlDataSource submit = new MysqlDataSource();
            submit.setServerName("localhost");
            submit.setUser("root");
            submit.setPassword("");
            submit.setPortNumber(3306);
            submit.setDatabaseName("private_musik");
            
            Connection koneksi=submit.getConnection();
            Statement state = koneksi.createStatement();
            String query = "SELECT MAX(Right(Id_Pengajar,2)) as no FROM pengajar";
            
            ResultSet rs = state.executeQuery(query);
            while(rs.next()){
                if(rs.last()){
                    rs.last();
                    int auto_id = rs.getInt(1)+1;
                    String no = String.valueOf(auto_id);
                    int noLong = no.length();
                                for(int a=0;a<3-noLong;a++){
                                    no = "0" + no;
                                }
                    txtidpengajar.setText("P"+no);
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "error \n"+ e.toString(),"Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void cekusername(){
        String user=txtuserpengajar.getText();
        if(user.equals("")){
            JOptionPane.showMessageDialog(null, "Username kosong!");
        }else{
            try{
                MysqlDataSource submit = new MysqlDataSource();
                submit.setServerName("localhost");
                submit.setUser("root");
                submit.setPassword("");
                submit.setPortNumber(3306);
                submit.setDatabaseName("private_musik");

                Connection koneksi=submit.getConnection();

                ResultSet rs = koneksi.prepareStatement("select Username from pengajar where"+
                        " Username='"+txtuserpengajar.getText()+"'").executeQuery();                       
                    if(rs.next()){
                        JOptionPane.showMessageDialog(null, "Username sudah digunakan!");
                    }else{
                        JOptionPane.showMessageDialog(null, "Username dapat digunakan!");
                    }                
            }catch(Exception e){
                System.out.println(e);

            }
        }        
    }
}
