/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesar_privatemusik;
import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ronaldo
 */
public class UpdateDataSiswaAdmin extends javax.swing.JFrame {
    DefaultTableModel tabelmodel;
    int mousePX;
    int mousePY;
    Beranda del = new Beranda();
    /**
     * Creates new form UpdateDataSiswa
     */
    public UpdateDataSiswaAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        
        String[] judul={"Id Siswa","Nama Siswa","Jenis Kelamin","Alamat","Username","Password"};
        tabelmodel = new DefaultTableModel(null, judul);
        tabelsiswaadmin.setModel(tabelmodel);

        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        txtusersiswa = new javax.swing.JTextField();
        txtpasssiswa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtidsiswa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnamasiswa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtkelaminsiswa = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamatsiswa = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelsiswaadmin = new javax.swing.JTable();
        mize = new javax.swing.JLabel();
        tutup1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backlogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 55, 153));
        jLabel9.setText("Username");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(200, 250, 100, 20);

        txtusersiswa.setBackground(new java.awt.Color(204, 204, 204));
        txtusersiswa.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        txtusersiswa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtusersiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusersiswaActionPerformed(evt);
            }
        });
        getContentPane().add(txtusersiswa);
        txtusersiswa.setBounds(370, 250, 220, 30);

        txtpasssiswa.setBackground(new java.awt.Color(204, 204, 204));
        txtpasssiswa.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        txtpasssiswa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpasssiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasssiswaActionPerformed(evt);
            }
        });
        getContentPane().add(txtpasssiswa);
        txtpasssiswa.setBounds(370, 290, 220, 30);

        jLabel10.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(30, 55, 153));
        jLabel10.setText("Password");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(200, 290, 100, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonHapus.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(660, 550, 100, 30);

        jLabel4.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 55, 153));
        jLabel4.setText("Id Siswa");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 60, 130, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonCari.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(600, 60, 100, 30);

        txtidsiswa.setBackground(new java.awt.Color(204, 204, 204));
        txtidsiswa.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        txtidsiswa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidsiswaActionPerformed(evt);
            }
        });
        getContentPane().add(txtidsiswa);
        txtidsiswa.setBounds(370, 60, 220, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonUpdate.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(550, 550, 100, 30);

        jLabel3.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 55, 153));
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 100, 60, 20);

        txtnamasiswa.setBackground(new java.awt.Color(204, 204, 204));
        txtnamasiswa.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        txtnamasiswa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnamasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamasiswaActionPerformed(evt);
            }
        });
        txtnamasiswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnamasiswaKeyTyped(evt);
            }
        });
        getContentPane().add(txtnamasiswa);
        txtnamasiswa.setBounds(370, 100, 220, 30);

        jLabel6.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 55, 153));
        jLabel6.setText("Jenis Kelamin");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 140, 130, 23);

        txtkelaminsiswa.setBackground(new java.awt.Color(204, 204, 204));
        txtkelaminsiswa.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 11)); // NOI18N
        txtkelaminsiswa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-Laki", "Perempuan" }));
        txtkelaminsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkelaminsiswaActionPerformed(evt);
            }
        });
        getContentPane().add(txtkelaminsiswa);
        txtkelaminsiswa.setBounds(370, 140, 91, 30);

        jLabel7.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 55, 153));
        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 180, 80, 23);

        txtalamatsiswa.setBackground(new java.awt.Color(204, 204, 204));
        txtalamatsiswa.setColumns(20);
        txtalamatsiswa.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtalamatsiswa.setRows(5);
        jScrollPane1.setViewportView(txtalamatsiswa);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(370, 180, 300, 60);

        tabelsiswaadmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelsiswaadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelsiswaadminMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelsiswaadmin);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(43, 333, 720, 210);

        mize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mize.setForeground(new java.awt.Color(255, 255, 255));
        mize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonMinimize.png"))); // NOI18N
        mize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mizeMouseClicked(evt);
            }
        });
        getContentPane().add(mize);
        mize.setBounds(750, 0, 20, 30);

        tutup1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tutup1.setForeground(new java.awt.Color(255, 255, 255));
        tutup1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonExit.png"))); // NOI18N
        tutup1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tutup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutup1tutupMouseClicked(evt);
            }
        });
        getContentPane().add(tutup1);
        tutup1.setBounds(770, 0, 20, 30);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 40);

        backlogin.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 14)); // NOI18N
        backlogin.setForeground(new java.awt.Color(255, 255, 255));
        backlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonBack.png"))); // NOI18N
        backlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backloginMouseClicked(evt);
            }
        });
        getContentPane().add(backlogin);
        backlogin.setBounds(40, 550, 100, 30);

        jLabel1.setForeground(new java.awt.Color(30, 55, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundUpdate.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidsiswaActionPerformed
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_txtidsiswaActionPerformed

    private void txtnamasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamasiswaActionPerformed

    private void txtkelaminsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkelaminsiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkelaminsiswaActionPerformed

    private void tabelsiswaadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelsiswaadminMouseClicked
        // TODO add your handling code here:
        int baris = tabelsiswaadmin.getSelectedRow();
        String idsiswa = (String)tabelmodel.getValueAt(baris, 0);
        String nama = (String)tabelmodel.getValueAt(baris, 1);
        String jeniskelamin = (String)tabelmodel.getValueAt(baris, 2);
        String alamat = (String)tabelmodel.getValueAt(baris, 3);
        String username = (String)tabelmodel.getValueAt(baris, 4);
        String password = (String)tabelmodel.getValueAt(baris, 5);
        
        txtidsiswa.setText(idsiswa);
        txtnamasiswa.setText(nama);
        txtkelaminsiswa.setSelectedItem(jeniskelamin);
        txtalamatsiswa.setText(alamat);
        txtusersiswa.setText(username);
        txtpasssiswa.setText(password);
    }//GEN-LAST:event_tabelsiswaadminMouseClicked

    private void backloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backloginMouseClicked
        // TODO add your handling code here:
        dispose();
        new FormAdmin().setVisible(true);
    }//GEN-LAST:event_backloginMouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        // TODO add your handling code here:
        int koordinatX = evt.getXOnScreen();
        int koordinatY = evt.getYOnScreen();

        this.setLocation(koordinatX-mousePX, koordinatY-mousePY);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void mizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mizeMouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_mizeMouseClicked

    private void tutup1tutupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutup1tutupMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tutup1tutupMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        int jawab = JOptionPane.showConfirmDialog(null, "Apakah anda Ingin Menghapus?");
        
        switch(jawab){
            case JOptionPane.YES_OPTION:
                if(tabelsiswaadmin.getSelectedColumnCount()!=-1){
                    try{
                        MysqlDataSource submit = new MysqlDataSource();
                        submit.setServerName("localhost");
                        submit.setUser("root");
                        submit.setPassword("");
                        submit.setPortNumber(3306);
                        submit.setDatabaseName("private_musik");

                        Connection koneksi=submit.getConnection();

                        koneksi.prepareStatement(
                        "DELETE FROM siswa WHERE Id_Siswa= '"+txtidsiswa.getText()+"'").executeUpdate();
                        del.daftarsiswa.remove(txtidsiswa.getText());
                        tampil();
                        txtidsiswa.setText("");
                        txtnamasiswa.setText("");
                        txtkelaminsiswa.setSelectedItem("Laki-Laki");
                        txtalamatsiswa.setText("");
                        txtusersiswa.setText("");
                        txtpasssiswa.setText("");
                    }catch(Exception e){
                        System.out.println(e);
                    }
                }
                break;
            case JOptionPane.NO_OPTION:
                break;
            case JOptionPane.CANCEL_OPTION:
                break;
        }        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        String nama=txtnamasiswa.getText();
        String alamat=txtnamasiswa.getText();
        String user=txtusersiswa.getText();
        String pass=txtpasssiswa.getText();
        
        if(nama.equals("")||alamat.equals("")||user.equals("")||pass.equals("")){
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!");
        }else{
            try{
                MysqlDataSource submit = new MysqlDataSource();
                submit.setServerName("localhost");
                submit.setUser("root");
                submit.setPassword("");
                submit.setPortNumber(3306);
                submit.setDatabaseName("private_musik");

                Connection koneksi=submit.getConnection();

                koneksi.prepareStatement(
                        "update siswa set Nama_Siswa = '"+txtnamasiswa.getText()+
                        "', Jenis_Kelamin = '"+txtkelaminsiswa.getSelectedItem()+
                        "', Alamat = '"+txtalamatsiswa.getText()+
                        "', Username = '"+txtusersiswa.getText()+
                        "', Password = '"+txtpasssiswa.getText()+
                        "'where Id_Siswa= '"+txtidsiswa.getText()+"'").execute();

                tampil();
                JOptionPane.showMessageDialog(null, "Data berhasil di perbaharui!");
                txtidsiswa.setText("");
                txtnamasiswa.setText("");
                txtkelaminsiswa.setSelectedItem("Laki-Laki");
                txtalamatsiswa.setText("");
                txtusersiswa.setText("");
                txtpasssiswa.setText("");
            }catch(Exception e){
                System.out.println(e);

            }
        }        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void txtusersiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusersiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusersiswaActionPerformed

    private void txtpasssiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasssiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasssiswaActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void txtnamasiswaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamasiswaKeyTyped
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtnamasiswaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDataSiswaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDataSiswaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDataSiswaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDataSiswaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDataSiswaAdmin().setVisible(true);
            }
        });
    }
    
    public void tampil() {
        int baris = tabelmodel.getRowCount();
        for(int i=1;i<=baris;i++){
            tabelmodel.removeRow(0);
        }
        
        try{
            MysqlDataSource submit = new MysqlDataSource();
            submit.setServerName("localhost");
            submit.setUser("root");
            submit.setPassword("");
            submit.setPortNumber(3306);
            submit.setDatabaseName("private_musik");
            
            Connection koneksi=submit.getConnection();
            
            ResultSet rs = koneksi.prepareStatement("select Id_Siswa,"+
                    "Nama_Siswa,Jenis_Kelamin,Alamat,Username,Password from siswa").executeQuery();
                while(rs.next()){
                    tabelmodel.addRow(new  String[]{
                        rs.getString(1),
                        rs.getString(2),
                        rs.getString(3),
                        rs.getString(4),
                        rs.getString(5),
                        rs.getString(6)}
                    );
                }
            
        }catch(Exception e){
            System.out.println(e);
            
        }
    }
    
    public void cari(){
        try{
            MysqlDataSource submit = new MysqlDataSource();
            submit.setServerName("localhost");
            submit.setUser("root");
            submit.setPassword("");
            submit.setPortNumber(3306);
            submit.setDatabaseName("private_musik");
            
            Connection koneksi=submit.getConnection();
            
            ResultSet rs = koneksi.prepareStatement("select Nama_Siswa,"+
                    "Jenis_Kelamin,Alamat,Username,Password from siswa "+
                    "where Id_Siswa='"+txtidsiswa.getText()+"'").executeQuery();
                if(rs.next()){
                    txtnamasiswa.setText(rs.getString(1));
                    txtkelaminsiswa.setSelectedItem(rs.getString(2));
                    txtalamatsiswa.setText(rs.getString(3));
                    txtusersiswa.setText(rs.getString(4));
                    txtpasssiswa.setText(rs.getString(5));
                }else{
                    JOptionPane.showMessageDialog(null, "Data siswa tidak ditemukan!");
                    txtidsiswa.setText("");
                    txtnamasiswa.setText("");
                    txtkelaminsiswa.setSelectedItem("Laki-laki");
                    txtalamatsiswa.setText("");
                    txtusersiswa.setText("");
                    txtpasssiswa.setText("");
                }            
        }catch(Exception e){
            System.out.println(e);
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mize;
    private javax.swing.JTable tabelsiswaadmin;
    private javax.swing.JLabel tutup1;
    private javax.swing.JTextArea txtalamatsiswa;
    private javax.swing.JTextField txtidsiswa;
    private javax.swing.JComboBox txtkelaminsiswa;
    private javax.swing.JTextField txtnamasiswa;
    private javax.swing.JTextField txtpasssiswa;
    private javax.swing.JTextField txtusersiswa;
    // End of variables declaration//GEN-END:variables
}
